# Wazuh App Copyright (C) 2017, Wazuh Inc. (License GPLv2)
version: '3.9'

services:
  generator:
    image: wazuh/wazuh-certs-generator:0.0.1
    hostname: wazuh-certs-generator
    volumes:
      - ./config/wazuh_indexer_ssl_certs/:/certificates/
      - ./config/certs.yml:/config/certs.yml
    environment:
      - HTTP_PROXY=YOUR_PROXY_ADDRESS_OR_DNS

# docker-compose -f generate-indexer-certs.yml run --rm generator
# This saves the certificates into the config/wazuh_indexer_ssl_certs directory. In case you have your own certificates, provision them as follows in the config/wazuh_indexer_ssl_certs directory

# docker-compose up -d